package com.maillardmap.ui.map

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.LazyRow
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.lazy.rememberLazyListState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material.*
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.Shape
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.mapbox.geojson.Feature
import com.mapbox.geojson.Point
import com.mapbox.maps.extension.compose.MapboxMap
import com.mapbox.maps.extension.compose.animation.viewport.rememberMapViewportState
import com.mapbox.maps.extension.style.layers.geoJson
import com.mapbox.maps.extension.style.layers.geoJsonSource
import com.mapbox.maps.extension.style.layers.point
import com.mapbox.maps.extension.style.layers.point.PointLayer
import com.mapbox.maps.extension.style.layers.point.PointLayerProperties
import com.mapbox.maps.extension.style.sources.geoJson
import com.mapbox.maps.plugin.locationcomponent.location
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.locationcomponent.locationComponent
import com.mapbox.maps.plugin.location